name: Pipeline Python Simples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # ou a versão que preferir

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "requirements.txt não encontrado, continuando..."

      - name: Rodar o script Python
        run: |
          python jogo.py  # Aqui você roda o arquivo principal do seu projeto
