name: CI Simples

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: pytest

      - name: Executar o jogo com argumentos
        run: |
          python jogo.py --nome_jogo "Valorant" --nome_pessoa "Leonardo" --personagem "Jett" --vitorias 10 --derrotas 5 --eliminacoes 50 --mortes 20
