name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar testes
      run: |
        pytest

    - name: Executar o jogo com argparse
      run: |
        python jogo.py \
          --nome_jogo "Valorant" \
          --nome_pessoa "Leonardo" \
          --personagem "Jett" \
          --vitorias 10 \
          --derrotas 5 \
          --eliminacoes 50 \
          --mortes 20


